packages:
  - packages/libs/*
  - packages/apps/*

allowBuilds:
  better-sqlite3: true
  esbuild: true

minimumReleaseAgeExclude:
  - '@multiterm/rune@0.4.1-b.15'
  - '@multiterm/release-sdk@0.4.1-b.18'
  - '@multiterm/release@0.4.1-b.18'
