export default {
  versioning: 'independent',
  packages: ['packages/apps/cli', 'packages/apps/mcp'],
  branches: ['develop', 'main'],
  branchChannels: { develop: 'beta', main: 'latest' },
  prereleaseIds: { beta: 'b' },
  packageManager: 'pnpm',
  checks: ['rune build', 'rune test'],
  access: 'public',
  github: true,
  localWorkspaceDirectories: [
    '../../haystack/core',
    '../../keyname/core',
    '../../sandblocks/core',
    '../../keypost/core',
    '../../WRLD/honeycluster/cron',
    '../../WRLD/honeycluster/indexer',
    '../../WRLD/honeycluster/validators',
    '../../WRLD/honeycluster/portal',
    '../../WRLD/honeycluster/drones',
    '../../WRLD/crossmark/core',
  ],
  updateLocalWorkspaceLockfiles: false,
};
